### error
Parser Error: Int cannot have a subtype.
 --> test/unit_tests/TypeCannotHaveSubtype.silly
16 | 
17 | def Something(a: int int) -> int:
                          ^^^^ this should not have a type before it
18 | 	123;

Parser Error: Unexpected content encountered that does not match SillyScript syntax.
 --> test/unit_tests/TypeCannotHaveSubtype.silly
16 | 
17 | def Something(a: int int) -> int:
                             ^ unexpected content encountered
18 | 	123;
###

def Something(a: int int) -> int:
	123;

Something(123);
